### ISSUE TITLE
Erro Decriptado

### ISSUE THREAD

**Issue by LucasDiasNardino** [LucasDiasNardino/GameFDS#3]
<h1>Erro na classe GraficosObservable</h1>
<p>
Há um erro de decriptação na classe GraficosObservable, que impede a conclusão do exercício devido ao fator que a classe observer está decriptada desde o java 9. Falar c Agustini para resolver.
</p>
<code>this.notifyObservers();</code><br>
<code>The type Observable cannot be a superinterface of GraficosObservable; a superinterface must be an interfaceJava(16777531)</code>

**Comment by LucasDiasNardino** [comment]
<h1>Como Resolver</h1>
<ul>
<li>Cria-se interface notificação, e classes do grafico e da tabela que avisam a interface.</li><br>
<li>Subject é a aplicação, que implementa uma lista de 0 ou mais inrteressados c coleção que vem da interface notificação. Também possui um register e um notify</li>
</ul>

**Comment by Enzo-Neves** [comment]
<h1> classe eventmanager </h1>

<code>

public class EventManager {
    Map<String, List<EventListener>> listeners = new HashMap<>();

    public EventManager(String... operations) {
        for (String operation : operations) {
            this.listeners.put(operation, new ArrayList<>());
        }
    }

    public void subscribe(String eventType, EventListener listener) {
        List<EventListener> users = listeners.get(eventType);
        users.add(listener);
    }

    public void unsubscribe(String eventType, EventListener listener) {
        List<EventListener> users = listeners.get(eventType);
        users.remove(listener);
    }

    public void notify(String eventType, File file) {
        List<EventListener> users = listeners.get(eventType);
        for (EventListener listener : users) {
            listener.update(eventType, file);
        }
    }
}

</code>
